{
 "title": "skillbox_dashoard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": { "query": "label_values(up,env)" } }
  ]
 },
 "panels": [
  {
   "title": "node_status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{env=\"$env\", type=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "app_up",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{env=\"$env\", type=\"application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load15{env=\"$env\", type=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}