- name: Setup monitoring
  hosts: monitoring
  become: yes
  vars:
    app_ip: "127.0.0.1"  
    prometheus_host: "host.docker.internal"

  tasks:
    - name: Install Packages
      apt:
        name:
          - apt-transport-https  
          - ca-certificates  
          - software-properties-common
          - prometheus
          - prometheus-node-exporter  
        state: present
        update_cache: yes

    - name: Deploy Prometheus config
      copy: 
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        content: |
          global:
            scrape_interval: 15s
          
          scrape_configs:
            - job_name: prometheus
              static_configs:
                - targets: ['localhost:9090']
            
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['{{ app_ip }}:9100']
                  labels:
                    env: 'dev'

            - job_name: 'application'
              static_configs:
                - targets: ['{{ app_ip }}:8080']
                  labels: 
                    env: 'dev'

      notify: Restart Prometheus

    - name: Ensure node_exporter service is started
      systemd:
        name: prometheus-node-exporter
        state: started
        enabled: yes      

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
     
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes    
    
    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes      

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes     

    - name: Pull Grafana Docker Image
      docker_image:
        name: grafana/grafana
        tag: main-ubuntu
        source: pull

    - name: Create Grafana data directory
      file:
        path: /var/lib/grafana
        state: directory
        owner: "472"
        group: "472"
        mode: '0755'    
    
    - name: Create Grafana provisioning directory
      file:
        path: "/etc/grafana/provisioning/datasources"
        state: directory
        owner: "472"
        group: "472"
        mode: "0755"

    - name: Copy datasources configuration
      template:
        src: templates/datasources.j2
        dest: "/etc/grafana/provisioning/datasources/datasources.yml"
        owner: "472"
        group: "472"
        mode: "0644"      

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:main-ubuntu
        state: started
        restart_policy: always  
        ports:
          - "3000:3000"
        etc_hosts:
          host.docker.internal: host-gateway    
        volumes:
          - /var/lib/grafana:/var/lib/grafana
          - /etc/grafana/provisioning:/etc/grafana/provisioning  

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
