---
galaxy_info:
  author: deadman
  description: Monitoring setup with Prometheus and Grafana role
  company: Skillbox
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: common
  - role: docker
