---
- name: Setup skillbox devops services
  hosts: test_webserver:prod_webserver 
  become: yes

  roles:
    - common
    - docker
    - filebeat
    
  tasks:
    - name: Install prometheus-node-exporter
      apt:
        name: prometheus-node-exporter
        state: present
        update_cache: yes

    - name: Ensure node_exporter service is started and enabled
      systemd: 
        name: prometheus-node-exporter
        state: started
        enabled: yes


- name: Setup skillbox gitlab runner
  hosts: gitlabrunner 
  become: yes
  
  vars:
    test_application_ip: "{{ hostvars[groups['test_webserver'][0]].ansible_host }}"
    prod_application_ip: "{{ hostvars[groups['prod_webserver'][0]].ansible_host }}"
    gitlab_runner_registration_token: "{{ lookup('env','GITLAB_RUNNER_REGISTRATION_TOKEN') }}"
  
  roles:
    - common
    - docker
    - gitlab-runner

- name: Setup monitoring
  hosts: monitoring
  become: yes
  
  vars:
    test_application_ip: "{{ hostvars[groups['test_webserver'][0]].ansible_host }}"
    prod_application_ip: "{{ hostvars[groups['prod_webserver'][0]].ansible_host }}"
  
  roles:
    - common
    - docker
    - monitoring   
